---
kind: pipeline
type: kubernetes
name: docker-build

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.ahamon.ovh
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    dockerfile: k8s/Dockerfile
    repo: registry.ahamon.ovh/pydom
    tags:
    - ${DRONE_COMMIT_SHA:0:7}
    - latest
    platform: linux/arm64
  network_mode: host

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: kubernetes
name: deploy


steps:
  - name: deploy
    image: zc2638/drone-k8s-plugin
    pull: if-not-exists
    environment:
      TYDOM_PASS:
        from_secret: tydom_pass
      TYDOM_MAC:
        from_secret: tydom_mac
    settings:
      k8s_server: 
        from_secret: k8s_server
      k8s_token:
        from_secret: k8s_token
      k8s_ca_crt:
        from_secret: k8s_ca_crt
      k8s_skip_tls: true
      templates:
        - k8s/secret.yaml
        - k8s/deployment.yaml
      build_number: ${DRONE_COMMIT_SHA:0:7}
      tydom_pass: ${TYDOM_PASS}
      tydom_mac: ${TYDOM_MAC}


trigger:
  event:
  - promote
  target:
  - production
