---
kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.ahamon.ovh
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    repo: registry.ahamon.ovh/pydom
    tags:
    - ${DRONE_COMMIT_SHA:0:7}
    - latest
    platform: linux/arm64