---
kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.ahamon.ovh
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    dockerfile: k8s/Dockerfile
    repo: registry.ahamon.ovh/pydom
    tags:
    - ${DRONE_COMMIT_SHA:0:7}
    - latest
    platform: linux/arm64

---
kind: pipeline
type: kubernetes
name: default

steps:
- name: Deploy app
  image: danielgormly/drone-plugin-kube:0.0.1
  settings:
    template: path/to/deployment.yaml
    ca: LS0tLS1... # BASE64 encoded string of the K8s CA cert
    server: https://10.0.0.20:6443 # K8s master node address
    token:
      from_secret: kubernetes_token # Service account token to a service account that can manage deployments

trigger:
  event:
  - promote
  target:
  - production
